puts ("Now it's time to input your Speech Detail")
  puts ("Please enter your session number")
  puts ("1 ===================================>> Session 1")
  puts ("2 ===================================>> Session 2")
  session_no = gets().strip.to_i
  puts ("Please enter your speaker number")
  puts ("1 ===================================>> Speaker 1")
  puts ("2 ===================================>> Speaker 2")
  puts ("3 ===================================>> Speaker 3")
  puts ("4 ===================================>> Speaker 4")